# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filestorage', '0002_migrate_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='original_content_length',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
